version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=happy
      - POSTGRES_DB=msds
    networks:
      - psql
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  goapp:
    # go app
    container_name: goapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - psql

networks:
  psql:
    driver: bridge