version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=master
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    networks:
      - psql
    ports:
      - "5433:5432"

  goapp:
    # go app
    container_name: goapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2345:2345"
    restart: unless-stopped

volumes:
  postgres:

networks:
  psql:
    driver: bridge